# Generated by Django 4.2.5 on 2023-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='item_img',
        ),
        migrations.AddField(
            model_name='listings',
            name='item_imge',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
    ]
