# Generated by Django 4.2.5 on 2023-09-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_item_imge_listings_item_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='item_imgae',
            new_name='item_image',
        ),
    ]
