# Generated by Django 4.2.5 on 2023-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
