# Generated by Django 4.2.5 on 2023-09-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('clothing', 'Clothing'), ('house_hold_items', 'House hold items'), ('toys', 'Toys'), ('vehicle', 'Vehicles'), ('no_category', 'No specific category')], default='no_category', max_length=40),
        ),
    ]
